apiVersion: apps/v1
kind: Deployment
metadata:
  name: sisyphus-fastapi
spec:
  selector:
    matchLabels:
      run: sisyphus-fastapi
  template:
    metadata:
      labels:
        run: sisyphus-fastapi
    spec:
      containers:
      - name: sisyphus-fastapi
        image: oleksandran/sisyphus-fastapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        args:
          - '0.0.0.0'
          - '8080'
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 51m
            memory: 50Mi
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: MONGO_URI

---
apiVersion: v1
kind: Service
metadata:
  name: sisyphus-fastapi
  labels:
    run: sisyphus-fastapi
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    run: sisyphus-fastapi
